#!/usr/bin/env bash

# Get real path to this directory
dir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
real_path_to_this_script=$(realpath $dir/keyczar)
real_path_to_this_dir=$(dirname $real_path_to_this_script)
real_path_to_keyczar_jar=$real_path_to_this_dir/KeyczarTool-0.71f-060112.jar

javaopts="-Dlog4j.configuration=file://$real_path_to_this_dir/log4j.properties"

if [[ "$@" =~ --location= ]]
then
  java $javaopts -jar $real_path_to_keyczar_jar "$@"
else
  java $javaopts -jar $real_path_to_keyczar_jar "$@" --location=$(pwd)
fi

